<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    

<head>
        <meta charset="utf-8">
        <title>baildy template</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">

        <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->

        <link rel="stylesheet" href="css/normalize.css">
        <link rel="stylesheet" href="css/main.css">
        <link rel="stylesheet" href="css/global.css">
        <link rel="stylesheet" href="css/responsive.css">
        <!-- filtre effet sur video  -->

    </head>
    <body>
    
    	<div id="mask">   
            <div class="loader">
              <img src="img/282.gif" alt='loading'>
            </div>
        </div>
        	<?php  echo $this->layout()->content; ?>

        <a href="#" class="scrollup">^</a>
        <div id="maps">
			<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
            <div class="map-content">
            	<div class="wpgmappity_container inner-map" id="wpgmappitymap"></div>
            </div>
        </div>
        <div class="socialFooter">
        	<div class="social-icons">
                <div class="social">
                    <a href="https://es-es.facebook.com/" target="_blank"><div class="face"></div></a>
                    <a href="https://twitter.com/" target="_blank"><div class="twitt"></div></a>
                    <a href="https://plus.google.com/" target="_blank"><div class="plus"></div></a>
                </div>
            </div>
            <div class="clear"></div>
            <div class="copy">2013 © Solido. All rights reserved.</div>            
        </div>
        
        <script src="js/vendor/modernizr-2.6.2.min.js"></script>
        <script src="ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.9.1.min.js"><\/script>')</script>
        <script src="ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js"></script>
        <script src="js/main.js"></script>
        <!-- pages about  -->
        <script type="text/javascript" src="js/jquery.inview.js"></script>
        <script type="text/javascript" 	src="js/jquery.sticky.js"></script>
        <script type="text/javascript" 	src="js/portfolio.js"></script>

        <script type="text/javascript" src="js/jquery.hoverdir.js"></script>
        <script src="js/jquery.nav.js"></script>
        <script src="js/popup/jquery.magnific-popup.js"></script> 
				<script src="js/jquery.isotope.min.js"></script>
        <script src="js/plugins.js"></script>
        <script src="js/jquery.validate.js"></script>
        <script src="js/test.js"></script>
    </body>

</html>

	